import {connect} from 'react-redux'
import DeviceManageView2 from '../components/DeviceManageView'

const mapStateToProps = (state) => {
    return {
        ...state.deviceManage.base,
        table:state.deviceManage.table
    }
}

import {
    reloadTable,
    addList,
    addDeviceInfo,
    addPropertyInfo,
    addParamInfo,
    savePropertyInfo,
    saveId,
    clearPropertyData,
    delList,
    modifyList,
    searchList,
    onListSearch,
    searchRecord,
    addFunction,
    modifyFunction,
    removeFunction,
    removeList,
    hide,
    show,
    hideModify,
    showModify,
    hideAdd,
    showAdd,
    hideExamine,
    showExamine,
    hideAgain,
    showAgain,
    hideDetails,
    showDetails,
    examineFunction,
    searchInsUser,
    distribute,
    careData,
    careLoading,
    click,
    careShowModel,
    careRender,
    careSelectIds,
    careAdvance,
    careAdvanceModel,
    careAudit,
    careAuditModel,
    careDetails,
    careDetailsModel,
    treeTable,
    getAssetTemplate,
    saveDeviceName,
    setActiveKey,
    setModyActiveKey,
    saveParamInfo,
    modyPropertyInfo,
    saveCurNewEquipId,
    saveData
} from '../modules/TableModule'
import {
    showModal,
    hideModal
} from '../modules/DeviceManageModule'

const mapActionCreator = {
    reloadTable,
    showModal,
    hideModal,
    addList,
    addDeviceInfo,
    addPropertyInfo,
    addParamInfo,
    savePropertyInfo,
    saveId,
    clearPropertyData,
    delList,
    modifyList,
    searchList,
    onListSearch,
    searchRecord,
    addFunction,
    modifyFunction,
    removeFunction,
    removeList,
    hide,
    show,
    hideModify,
    showModify,
    hideAdd,
    showAdd,
    hideExamine,
    showExamine,
    hideAgain,
    showAgain,
    hideDetails,
    showDetails,
    examineFunction,
    onListSearch,
    searchInsUser,
    distribute,
    careData,
    careLoading,
    click,
    careShowModel,
    careRender,
    careSelectIds,
    careAdvance,
    careAdvanceModel,
    careAudit,
    careAuditModel,
    careDetails,
    careDetailsModel,
    treeTable,
    getAssetTemplate,
    saveDeviceName,
    setActiveKey,
    setModyActiveKey,
    saveParamInfo,
    modyPropertyInfo,
    saveCurNewEquipId,
    saveData
}



export default connect(mapStateToProps,mapActionCreator)(DeviceManageView2)